Feature/se 5 handle date
dataquest-dev/dspace-angular pull request #21
Opened 2022-04-12 07:41 UTC by milanmajchrak

| Phases            | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|-----:|-----:|-------:|
| ETA                  |  0.6  |    0 |     0 |      0 |        0 |
| Developing      |  1.5  |    0 |    0 |      0 |         0 |
| Review             |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -   |   -     |        0 |
## Problem description
Date of creation of some items has unknown or in date range. This information is stored in the approximateDate metadata. If approximateDate metadata is not null show value from this metadata.
### Reported issues
### Not-reported issues

2022-04-12 13:52 UTC, vidiecan requested changes

2022-04-12 13:52 UTC, vidiecan commented on src/app/item-page/item-page.resolver.ts
> +
why?

2022-05-23 13:22 UTC, milanmajchrak commented on src/app/item-page/item-page.resolver.ts
> +        const copiedRd = _.cloneDeep(rd);
@vidiecan I found used _cloneDeep_ in the DSpace7: https://github.com/DSpace/dspace-angular/blob/main/src/app/item-page/edit-item-page/item-metadata/item-metadata.component.ts#L129

2022-05-23 13:22 UTC, milanmajchrak commented on src/app/item-page/item-page.resolver.ts
> +        const copiedRd = _.cloneDeep(rd);
@vidiecan I found used _cloneDeep_ in the DSpace7: https://github.com/DSpace/dspace-angular/blob/main/src/app/item-page/edit-item-page/item-metadata/item-metadata.component.ts#L129

2022-05-23 13:23 UTC, milanmajchrak commented on src/app/item-page/item-page.resolver.ts
> +        const copiedRd = _.cloneDeep(rd);
maybe using cloneDeep is not so bad idea

2022-05-23 13:23 UTC, milanmajchrak commented on src/app/item-page/item-page.resolver.ts
> +        const copiedRd = _.cloneDeep(rd);
maybe using cloneDeep is not so bad idea

2022-05-27 12:55 UTC, closed without merging