ufal/fe-item-view-license-box
dataquest-dev/dspace-angular pull request #427
Opened 2023-12-15 14:29 UTC by milanmajchrak

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description

2023-12-18 12:37 UTC, vidiecan requested changes

2023-12-18 12:37 UTC, vidiecan commented on src/app/item-page/simple/item-page.component.html
> +          <div id="command-div" *ngIf="isCommandLineVisible">
why?

2023-12-18 12:38 UTC, vidiecan approved these changes

2023-12-19 08:24 UTC, milanmajchrak commented on src/app/item-page/simple/item-page.component.html
> +          <div id="command-div" *ngIf="isCommandLineVisible">
Fixed

2023-12-19 08:26 UTC, merged