ufal/fe-show-checksum-result
dataquest-dev/dspace-angular pull request #432
Opened 2023-12-27 18:52 UTC by milanmajchrak

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  16  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description

2024-01-02 16:58 UTC, vidiecan requested changes

2024-01-02 16:58 UTC, vidiecan commented on src/assets/i18n/cs.json5
> +  "item.edit.bitstreams.checksum.active-store": "Aktívne úložisko",
cestina!

2024-01-03 07:00 UTC, milanmajchrak commented on src/assets/i18n/cs.json5
> +  "item.edit.bitstreams.checksum.active-store": "Aktívne úložisko",
Fixed

2024-01-03 07:39 UTC, vidiecan approved these changes

2024-01-03 07:50 UTC, merged