Fixed harvest.bat
dataquest-dev/dspace-angular pull request #53
Opened 2022-06-16 13:37 UTC by milanmajchrak

| Phases            | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|-----:|-----:|-------:|
| ETA                  |  0.2  |    0 |     0 |      0 |        0 |
| Developing      |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -   |   -     |        0 |
## Problem description
changed harvest.bat

2022-07-25 12:34 UTC, MajoBerger approved these changes

2022-08-03 15:15 UTC, MajoBerger requested changes

2022-08-03 15:15 UTC, MajoBerger commented on build-scripts/import/harvest.bat
> +docker-compose --env-file %ENVFILE% -p dq-d7 -f docker/cli.yml -v %cd%/build-scripts/import/assets:/assets run --rm dspace-cli structure-builder -f /assets/test_community_collection.xml -o /assets/te
this change is useless

2023-06-22 12:29 UTC, milanmajchrak commented
@MajoBerger could we close this PR?

2023-06-22 12:37 UTC, MajoBerger commented
I don't know. I was never using harvesting... We could ignore it possibly.

2023-06-22 12:50 UTC, milanmajchrak commented
Harvesting works, I'm closing it.

2023-06-22 12:50 UTC, closed without merging