Feature/se 11 create user on dev5
dataquest-dev/dspace-angular pull request #59
Opened 2022-07-14 07:18 UTC by milanmajchrak

| Phases            | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  3  |    0 |    0 |      0 |         0 |
| Review             |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -   |   -     |        0 |
## Problem description
The test user doesn't exist in the dev5, create it for test purposes.

### Reported issues
Loading error: https://github.com/dataquest-dev/dspace-angular/issues/58

## Problems
### 1. Loading error
I cannot login after I created an user or admin as administrator on the _dev5_, the page just freezes in logging process with loading icon. In the console the FE throws error: 
![image](https://user-images.githubusercontent.com/90026355/178921052-a0d35bde-87c9-4b5c-bc46-f41a70097643.png)

I was trying to reproduce this error on local docker. I just built the dataquest docker images locally and tryied to create user as administrator. But the error doesn't occured, I successfuly logged in as the user. That means there is problem with dev5.

**Temporary solution:** The admin is successfuly added to the dev5 from the github action. I just added command to create a new user after creating a new admin in the _building_scripts/run/start_.

2022-07-14 10:27 UTC, MajoBerger requested changes
use some normal name for user please. John Doe or something...

2022-07-14 10:34 UTC, MajoBerger commented on build-scripts/run/start.bat
>  docker-compose --env-file %ENVFILE% -p dq-d7 -f docker/cli.yml run --rm dspace-cli create-administrator -e test@test.edu -f admin -l user -p admin -c en
I propose to change this as well as following line to unify mails. 
e.g. admin@test.edu and user@test.edu

2022-07-14 10:35 UTC, MajoBerger requested changes
unify login mails

2022-07-14 10:37 UTC, milanmajchrak commented on build-scripts/run/start.bat
>  docker-compose --env-file %ENVFILE% -p dq-d7 -f docker/cli.yml run --rm dspace-cli create-administrator -e test@test.edu -f admin -l user -p admin -c en
fixed

2022-07-14 10:50 UTC, MajoBerger approved these changes

2022-08-03 15:35 UTC, MajoBerger commented
User is created already, this is old and not up to date

2022-08-03 15:35 UTC, closed without merging