License label - do not require icon and Edit license - correctly loaded required info
dataquest-dev/dspace-angular pull request #595
Opened 2024-04-11 16:28 UTC by milanmajchrak

Fixed: https://github.com/dataquest-dev/dspace-angular/issues/485 and https://github.com/dataquest-dev/dspace-angular/issues/571

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description

2024-04-12 10:48 UTC, MajoBerger approved these changes

2024-04-22 12:26 UTC, vidiecan requested changes

2024-04-22 12:26 UTC, vidiecan commented on src/app/clarin-licenses/clarin-license-table/clarin-license-table.component.ts
> +    if (!hasIcon) {
why not put this in the catch?

2024-04-23 07:12 UTC, milanmajchrak commented on src/app/clarin-licenses/clarin-license-table/clarin-license-table.component.ts
> +    if (!hasIcon) {
Refactored.

2024-04-23 17:23 UTC, vidiecan approved these changes

2024-04-24 07:06 UTC, merged