Migrated Vanilla cs messages into clarin 7.6.1. cs messages
dataquest-dev/dspace-angular pull request #669
Opened 2024-07-26 12:42 UTC by milanmajchrak

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description

2024-08-13 14:59 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "admin.access-control.groups.form.tooltip.editGroupPage": "Na této stránce můžete upravit vlastnosti a členy skupiny. V horní části můžete upravit název a popis skupiny, pokud se nejedá o skupinu a
> v části [the wiki](https://wiki.lyrasis.org/display/DSDOC7x/Create+or+manage+a+user+group)

`[the wiki]` plus nevim, jestli ten odkaz bude fungovat, a jestli je vubec rozumny ten odkaz v tomhle miste mit

2024-08-13 15:05 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "bitstream.edit.form.selectedFormat.hint": "Pokud formát není ve výše uvedeném seznamu, <b>vyberte \"format not in list\" výše</b> a popište v části \"Describe new format\".",
neprelozene casti. Proc?

2024-08-13 15:09 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "collection.curate.header": "Kurátorovat kolekci: {{collection}}",
🤣 ve v5 by to bylo Spravovat kolekci

2024-08-13 15:14 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "collection.edit.tabs.source.notifications.invalid.title": "Metadata neplatná",
Tohle bych asi nechal na tom původním `Neplatná metadata`

2024-08-13 15:16 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "collection.source.update.notifications.error.content": "Zadané nastavení bylo testováno a nefungovalo.",
otestováno

2024-08-13 15:18 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "community.create.sub-head": "Vytvořit dílčí komunitu pro komunitu {{ parent }}",
`Vytvořit podkomunitu v komunitě {{ parent }}`

2024-08-13 15:18 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "community.curate.header": "Kurátorství komunity: {{ community }}",
🤦‍♂️

2024-08-14 13:11 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "health-page.property.status": "Kód statusu",
original lepsi `Stavový kód`

2024-08-14 13:19 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "item.edit.item-mapper.description": "Toto je nástroj pro mapování záznamů, který umožňuje správcům mapovat tuto záznam na jiné kolekce. Můžete vyhledávat kolekce a mapovat je nebo procházet seznam
`... tuto záznam na ...` -> `tento záznam do`

2024-08-14 13:23 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "item.edit.metadata.edit.buttons.virtual": "Tato hodnota metadat je virtuální, tedy děděná z příbuzné entity. Nemůže být zděděna napřímo. Přidejte či odeberte příslušný vztah na záložce \"Vztahy\".
`tedy děděná z příbuzné entity` -> `tedy děděná z provázané (related) entity` ?

`Nemůže být zděděna napřímo` -> `Nemůže být změněna napřímo`

2024-08-14 13:24 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "item.edit.metadata.notifications.saved.content": "Vaše změny metadat této záznamu byly uloženy.",
této záznamu

2024-08-14 13:32 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "item.page.filesection.license.bundle": "Licence svazku",
svazek

2024-08-14 13:33 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "item.page.claim.button": "Prohlásit",
?

2024-08-14 14:10 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "item.version.history.table.action.hasDraft": "Nová verze nemůže být vytvořena, protože v historii verzí probíhá odesílání.",
...protože už existuje rozpracovaná nová verze. ?

2024-08-14 14:20 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "menu.section.icon.import": "Importovat sekci menu",
tyhle "menu sekce" jsou lehce divoky

2024-08-14 14:22 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "menu.section.registries": "Rejstřík",
Registry

2024-08-14 14:24 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "mydspace.results.no-date": "Žádny datum",
Žádné datum

2024-08-16 12:04 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "person.search.title": "Vyledatávání osob",
typo

2024-08-16 12:07 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "process.overview.delete.processing": "Smazává se {{count}} procesů. Počkejte prosím na úplné dokončení mazání. To může chvíli trvat.",
Maže se...

2024-08-16 12:21 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "search.filters.applied.f.supervisedBy": "Zkontrolováno",
.

2024-08-16 12:43 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "submission.sections.identifiers.no_handle": "Tomuto záznamu nybyl přidělen žádný handle.",
typo

2024-08-16 12:46 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "submission.sections.upload.header.policy.default.nolist": "Nahrané soubory v kolekci {{collectionName}} budou přístupné podle následující skupiny (skupin):",
`skupiny (skupin)` je divny

2024-08-16 12:47 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "submission.sections.upload.header.policy.default.withlist": "Vezměte prosím na vědomí, že nahrané soubory v kolekci {{collectionName}} budou kromě toho, co je explicitně rozhodnuto pro jednotlivý
`skupiny (skupin)` je divny

2024-08-16 12:49 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "submission.sections.sherpa.error.message": " ",
.

2024-08-16 13:01 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "uploader.processing": "(nyní je bezpečné tuto stránku zavřít)",
.

2024-08-16 13:04 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "person.page.orcid.sync-queue.send.error": "Podání do ORCID se nezdařilo",
Odeslání

2024-08-16 13:06 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "system-wide-alert.form.cancel": "Zrušir",
typo

2024-08-16 13:07 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "system-wide-alert.form.label.countdownTo.enable": "Povolit odpočítávací měřič",
.

2024-08-20 09:51 UTC, kosarko commented
@milanmajchrak https://github.com/dataquest-dev/dspace-angular/compare/ufal/update-localization..ufal:dspace-angular:ufal/update-localization nedari se mi to commitnout sem primo. Tak bud muzu udelat komplet novej PR, nebo se ti to podari cherry-picknout?

2024-08-27 09:15 UTC, vidiecan approved these changes

2024-08-27 09:17 UTC, vidiecan requested changes
@milanmajchrak update based on OK comments

2024-10-08 12:35 UTC, milanmajchrak commented on src/assets/i18n/cs.json5
> +  "collection.curate.header": "Kurátorovat kolekci: {{collection}}",
Curation task sa môže preložiť ako `Úloha správy`?

Vo v5 je Curation Tasks ako "Úlohy správy"

2024-10-21 10:55 UTC, kosarko requested changes
Jen ještě ty dva komentáře + používá se konzistentně "svazek" místo "bundle?"

2024-10-21 10:55 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "item.page.claim.button": "Prohlásit",
@milanmajchrak chybí mi k tomu kontext, ale nedává tam smysl spíš něco jako `Převzít`?

2024-10-21 10:55 UTC, kosarko commented on src/assets/i18n/cs.json5
> +  "search.filters.applied.f.supervisedBy": "Zkontrolováno",
@milanmajchrak opět bych to potřeboval vidět s většim kontextem, to je nějakej popis search filteru? To se týka "person" entity, závěrečné práce, nebo ještě něčeho jiného?

2024-10-29 14:38 UTC, milanmajchrak commented
> Jen ještě ty dva komentáře + používá se konzistentně "svazek" místo "bundle?"

1. Skontroloval som "svazek" vs "bundle" a nenašiel som nikde použitie slova "bundle", používa sa len "svazek".
2. Claim = převzít, to dáva zmysel
3. Supervised by: v tomto kontexte https://wiki.lyrasis.org/display/DSDOC7x/Supervision+Orders by som to preložil ako "pod dohledem", môže byť?
4.

2024-10-30 09:13 UTC, kosarko commented
ok

2024-11-01 15:40 UTC, kosarko approved these changes
Looks good

2024-11-04 13:23 UTC, merged