Ufal/share submission by email
dataquest-dev/dspace-angular pull request #720
Opened 2024-10-07 06:24 UTC by milanmajchrak

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description

2024-10-08 12:50 UTC, vidiecan requested changes

2024-10-08 12:50 UTC, vidiecan commented on src/app/change-submitter-page/change-submitter-page.component.ts
> +      console.log('Loading submitter from observable', workspaceItem);
?

2024-10-08 12:50 UTC, vidiecan commented on src/app/change-submitter-page/change-submitter-page.component.ts
> +    // Send GET request
?

2024-10-08 12:50 UTC, vidiecan commented on src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.ts
> +   */  canEditItem$: Observable<boolean>;
?

2024-10-11 13:29 UTC, milanmajchrak commented on src/app/change-submitter-page/change-submitter-page.component.ts
> +    // Send GET request
Removed, thank you

2024-10-11 13:29 UTC, milanmajchrak commented on src/app/change-submitter-page/change-submitter-page.component.ts
> +      console.log('Loading submitter from observable', workspaceItem);
Removed, thank you

2024-10-11 13:30 UTC, milanmajchrak commented on src/app/shared/mydspace-actions/workspaceitem/workspaceitem-actions.component.ts
> +   */  canEditItem$: Observable<boolean>;
Fixed

2024-10-14 15:04 UTC, vidiecan approved these changes

2024-10-17 14:23 UTC, merged