precommit file
dataquest-dev/dspace-angular pull request #736
Opened 2024-11-20 08:03 UTC by Paurikova2

| Phases            | MP | MM  |  MB  | MR |   JM | Total  |
|-----------------|----:|----:|----:|-----:|-----:|-------:|
| ETA                  |  0  |  0  |    0 |     0 |      0 |        0 |
| Developing      |  0.1  |  0  |    0 |    0 |      0 |         0 |
| Review             |  0  |  0  |    0 |    0 |      0 |         0 |
| Total                |   -  |   -  |   -   |  -    |   -    |         0 |
| ETA est.             |      |      |       |       |         |         0 |
| ETA cust.           |   -  |   -  |   -  |   -   |   -     |        0 |
## Problem description
A precommit is missing from the Angular project.
**Run precommit test:**
pre-commit install
pre-commit run --all-files

2024-11-20 08:03 UTC, Paurikova2 commented
@milanmajchrak Can you test it too?

2024-11-20 13:02 UTC, milanmajchrak requested changes
@Paurikova2 
`Prettier support for pre-commit has been moved to https://github.com/pre-commit/mirrors-prettier, please use the new repository.`

Please try another repo, or precommit

2024-11-21 07:46 UTC, Paurikova2 commented
@milanmajchrak I changed repo path. I had more than 3K changes. Can you test it too again?

2025-01-23 08:42 UTC, milanmajchrak commented
We won't use precommit in the FE projects because there is a lot of changes.

2025-01-23 08:42 UTC, closed without merging